# Generated by Django 3.0.2 on 2020-01-24 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billetera', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='saldo',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=8),
            preserve_default=False,
        ),
    ]
